version: "3.9"

# Docker Compose List Services Configuration
services:
  # Ollama Image AI Service
  ollama-ai:
    image: ollama/ollama:0.6.8
    container_name: ollama-ai
    volumes:
      - ollama:/root/.ollama:rw
    restart: always
    networks:
      ollama-ai-network:
        ipv4_address: "10.11.12.26"
  # Open Web UI (Ollama Web Interface like ChatGPT) Configuration
  ollama-open-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-open-web-ui
    volumes:
      - open-web-ui:/app/backend/data:rw
    ports:
      - ${OPEN_WEB_UI_HOST:-127.0.0.1}:${OPEN_WEB_UI_PORT:-8000}:8080
    environment:
      - OLLAMA_BASE_URL=http://10.11.12.26:11434
    restart: always
    networks:
      ollama-ai-network:
        ipv4_address: "10.11.12.27"
    depends_on:
      ollama-ai:
        condition: service_started
        required: true

# Docker Compose Volume
volumes:
  ollama:
    driver: local
  open-web-ui:
    driver: local

# Docker Compose Volume
networks:
  ollama-ai-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.11.12.24/29"
          gateway: "10.11.12.25"
