# !Disclaimer: This script / Docker Image is only a Personal Error Resolution related to missing Python3 Dependencies. 
# !Please visit the Official Open Web UI Web at https://github.com/open-webui/open-webui

# IMPORT BASE IMAGE
FROM ghcr.io/open-webui/open-webui:main

# Install Python Depencies
RUN pip install hf_xet